### ISSUE TITLE
Cisco Switch Connection Problem

### ISSUE THREAD

**Issue by canturkm** [bastillion-io/Bastillion#270]
Hello,

Firstly, thanks for the software. 

We don't use public key authentication. We only use passwords. When the public key auth fails, KeyBox asks for password and if the password is correct we login to device. 

This mechanism works with our Linux servers, however not works with our Cisco switches.

When we try to connect cisco switches with KeyBox, we get "channel not opened" error. 

Cisco 4500x switch
![cisco_switch_channel_not_opened3](https://user-images.githubusercontent.com/10234479/36963355-e79564b0-2063-11e8-968e-a2385393ecea.png)

I try to debug the code, it throws exception on addPubKey() method call inside SSHUtil.openSSHTermOnSystem() method (when password entered).

![cisco_switch_channel_not_opened4](https://user-images.githubusercontent.com/10234479/36963538-c76cae2c-2064-11e8-867b-0b2d97376288.png)
 
However, it doesn't look like on the first call. I couldn't resolve the function call scheme, and I didn't have so much time to debug.

However when I commented out the code (addPubKey() method call inside SSHUtil.openSSHTermOnSystem() method), it started to work.
![cisco_switch_channel_not_opened_connected_after_commenting_addpublickey](https://user-images.githubusercontent.com/10234479/36963593-f4ca4cb2-2064-11e8-989d-bd39ec7cefa2.png)

I solved the problem. However my solution is not optimal. Maybe you can find better solution for the bug.

Thanks.

**Comment by Crash0v3r1de** [comment]
Is this the only work around for the cisco switch issue? I'm having the same issue. I use username and password for auth and it thinks the login is invalid and gives the channel error.

**Comment by canturkm** [comment]
We only use KeyBox for Cisco switches. So, I have no idea for other workarounds.

**Comment by skavanagh** [comment]
I think I can figure out something with this. Maybe have it ignore the exception when adding the public key. I’ll try and have it in this weekends release. 

Sent from my iPhone
