### ISSUE TITLE
Consider supporting IP restricted SSH keys

### ISSUE THREAD

**Issue by neilwhitespace** [bastillion-io/Bastillion#288]
Some SSH public keys have an ip in the following format at the beginning:

```
from="192.168.0.0/24" ssh-rsa BLAHBLAHYOURKEYGOESHERE someone@somewhere
```

Please consider altering the validation to allow this.

**Comment by skavanagh** [comment]
+1

**Comment by TheBags** [comment]
It would be convenient to have the possibility of adding environment variables through the admin administrative interface.
The user normally does not know which variables to enter when he sends the ssh key.
Normally the anvs are added by the admin and can change during the time.
