### ISSUE TITLE
Instructions for first time admin login

### ISSUE THREAD

**Issue by ffabreti** [bastillion-io/Bastillion#289]
I am trying to setup keybox for the first time and I am supposed to change password by logging in as "admin" with password "changeme". but it is prompting for OTP Acess code.

Cannot find any instructions how to proceed, please advise.

**Comment by skavanagh** [comment]
Just leave the OTB blank on your first login.

**Comment by skavanagh** [comment]
You must have updated lmvc.. You need this fix -
https://github.com/skavanagh/KeyBox/commit/9a059c47c9dc687d126869ef7d8eaa8b47a5dc81#diff-7684a95e32b87e68425a24a215e25d4f

**Comment by ffabreti** [comment]
Thank you.
