### ISSUE TITLE
Weird Characters / ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by JessedeJonge** [bastillion-io/Bastillion#296]
When I try to build Bastillion from source or just use the Bastilion Jetty version and try to open the website in browser, Chrome returns a 'This page isn't working' with a err_invalid_http_response, and firefox is showing weird characters (see screenshot). 

Ubuntu 18.04 Server
![screenshot_20190305_092516](https://user-images.githubusercontent.com/14309234/53790998-9aceda00-3f28-11e9-8f52-1a8f911cf488.png)

**Comment by skavanagh** [comment]
http -> https

**Comment by JessedeJonge** [comment]
> http -> https

Just wow.. I am an idiot. Keeping this up for other newbies.
