### ISSUE TITLE
Authentication Failed : Login credentials are invalid - Current Build has repeatedly locked me out after configuration

### ISSUE THREAD

**Issue by abclution** [bastillion-io/Bastillion#298]
100% repeatable issue. Passwords double and triple checked and saved into a password manager as well.
Hi, this has happened now 2-3 times in a row, and my username/pw is 100% correct and I also believe i Know how to repeat the behavior.

Scenario

Fresh install extract on windows.
Login with admin / changeme
Setup a few hosts.
Change admin password (Actually this is not necessary)
Important: Then while looking at the hosts list open a new browser tab with the multiple ssh windows (Middle mouse click for new tab in Chrome in this case)
Tab2: Connect to some of the configured hosts in the multi ssh area.
After the next operation is attempted in the host list (first browswer tab), I will be logged out.
SSH term tab will keep running until closed, then will also be logged out.

Attempt to login with admin and password (changed or not) fails with 

Authentication Failed : Login credentials are invalid

No way other than a DB edit to get back in, and I don't know how to work with this kind of db to have a look what has happened to the password field.

**Comment by skavanagh** [comment]
Tabbed browsing doesn't work with the CSRF token that is present preventing cross-site forgery requests.  It will invalidate the token and log you out. It shouldn't have changed your credentials. I would try and close your browser and login again.

**Comment by abclution** [comment]
- CSRF token
Hi, I figured that was the case.

But no go, my credentials do not work after browser restart, cache clear, or Bastillion restart. Very odd and repeatable behavior.

**Comment by skavanagh** [comment]
The only thing I can think is you accidentally enabled the one-time password. Try setting this to 'disabled'

https://github.com/bastillion-io/Bastillion/blob/master/src/main/resources/BastillionConfig.properties#L28

and restarting

**Comment by abclution** [comment]
Woohoo, Yes, this fixed it but I had not many any changes.
oneTimePassword=optional
It was set to "optional" and setting it to "disabled" corrected the issue. Thank you.

The only config change I have made to the default config is:

keyManagementEnabled=false

which I forgot to include on the original setup steps...

Its very very strange.

**Comment by abclution** [comment]
BTW I saw this when you first posted it on reddit  (Called Keybox previously?) a few years ago but never got around to trying it until just now. I see you have started to market it and make it a service. Congrats, I thought it was a great idea back then and it stuck in my mind to try it out since then

**Comment by skavanagh** [comment]
Thank you.  If you ever re-enable the OTP you might want to create a "Full Access" user first.  So that the new user can reset the previous user's OTP

**Comment by abclution** [comment]
Yes I read about that as a backdoor/recovery method and my intent was to do it, but after losing access and nuking my config the first time (I assumed my own user error) I neglected to do it right away and this issue appeared again and I figured to file a bug report.

 I do believe it is a bug and probably the configuration should be set to disabled or whatever is wonky fixed.
