### ISSUE TITLE
Nothing happen after new user login

### ISSUE THREAD

**Issue by n4nd4r** [bastillion-io/Bastillion#300]
Hi, I'll try to explain this chronologically.
1. I tried to add a user, but failed due to free license limitation
2. So I told my boss to subscribe 1, and he did, got the license key and applied it
3. New users were added and assigned profiles to them

When I try to login as any of the new users, the web would be just stuck at https://[my_server]:8443/loginSubmit.ktrl

![image](https://user-images.githubusercontent.com/38689573/55955082-9bc2fc00-5c8a-11e9-9a6c-93ca9bc6551c.png)

Previously created users are fine, no problem

Steps I tried so far:
1. Delete the problematic users, recreate them, still no change.
2. Upgrade from 3.05.01 to 3.06.01, still no change
3. Check the audit session, no logs

Any idea what happened?

**Comment by skavanagh** [comment]
Does this still occur if you restart the jetty server?

**Comment by n4nd4r** [comment]
Yup, even rebooting the server doesn't help.

> Does this still occur if you restart the jetty server?
> […](#)
> Sent from my iPhone
> On Apr 11, 2019, at 8:06 AM, Achmad Sunandar ***@***.***> wrote: Hi, I'll try to explain this chronologically. I tried to add a user, but failed due to free license limitation So I told my boss to subscribe 1, and he did, got the license key and applied it New users were added and assigned profiles to them When I try to login as any of the new users, the web would be just stuck at https://[my_server]:8443/loginSubmit.ktrl Previously created users are fine, no problem Steps I tried so far: Delete the problematic users, recreate them, still no change. Upgrade from 3.05.01 to 3.06.01, still no change Check the audit session, no logs Any idea what happened? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by skavanagh** [comment]
What version of Java are you on?

**Comment by skavanagh** [comment]
also is there any errors that show in jetty/logs?
