### ISSUE TITLE
Use The Management Keys always get "Error: Auth fail" when login to web ssh

### ISSUE THREAD

**Issue by imadeput0287** [bastillion-io/Bastillion#315]
There is any complete guide to use Management Keys? I set it true, when add system it success, but when try to login to ssh after register bastillion says "Error: Auth fail". Please help. Thank you.

**Comment by selim-b** [comment]
Same here

**Comment by imadeput0287** [comment]
To anyone that have same question, you need to generate private key and public key using RSA on linux. Before I was use PuttyGen on Windows.
