### ISSUE TITLE
No users displayed after update to 3.08_00

### ISSUE THREAD

**Issue by netchild** [bastillion-io/Bastillion#317]
Hi,

I just update from 3.06_04 to 3.08_00. Admin user login works. I have one more user (default DB setup, no changes in the config for the DB). When I try to login with this user, I get the message that no profiles are attached to this user (in 3.06 which was my initial install I had assigned a profile to this user, before the update to 3.08 I made a successful login with this user). When I have a look at the user list as admin, I see nothing. The button "add user" is there, but below this button there is only empty space. If I try to add a new user with the same name as the one I'm missing, I get the message that this user exists.

Bye,
Alexander.

**Comment by netchild** [comment]
Uhm.. probably the list of users is shown above the "add user" button... above there is no list, only:
Manage Users
Add / Delete users below so that system profiles may be set for users (Manage Profiles).

**Comment by skavanagh** [comment]
Try running the upgrade on the new installation
```
java -jar bastillion-upgrade-3.08.00.jar <whatever path>/jetty/bastillion/WEB-INF/classes/BastillionConfig.properties
```
https://github.com/bastillion-io/Bastillion/releases/tag/v3.08.00

**Comment by netchild** [comment]
Yes, works. Thanks!
