### ISSUE TITLE
ssh key manage issues

### ISSUE THREAD

**Issue by pqhung1983** [bastillion-io/Bastillion#320]
in order to try bastillion before making decision to subscription it , I got issues on below scenarios:
step1: add ssh public key on dev profiles
step2: change user member of dev profiles

ssh dev key which I added on above step on `manage SSH keys` was disappeared .

BTW: when I try to upgrade from 3.06.04 to newest release 3.08.00  . another issues occured :
users list can not display and jetty error log:

> 2019-09-20 13:25:49,822 ERROR UserDB - org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "last_login_tm" not found [42122-199]
> org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "last_login_tm" not found

**Comment by skavanagh** [comment]
User's manage their own keys, when an admin removes them from a profile it will remove the key too.

The "Column "last_login_tm" not found" is fixed by running the upgrade jar on the database described in the 3.08.00 release notes - https://github.com/bastillion-io/Bastillion/releases/tag/v3.08.00

**Comment by pqhung1983** [comment]
But on this case, I just change member of users on `dev` profile.It does not make sense or issues if `manage SSH keys` remove the key on dev profile which another users are using it

**Comment by pqhung1983** [comment]
thanks for quick resolve this issues.It works like a charm.

Thanks,
HungPham
