### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH  after install

### ISSUE THREAD

**Issue by magadan** [bastillion-io/Bastillion#321]
Hello, i installed java, ok.

When run start script and tried to access webconsole 8443 i receive:

ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Need to do new certificates ?

8080 i receive connection refuse.

**Comment by skavanagh** [comment]
You should be able to accept and bypass the certificate warning..

but yes it is a great idea to install your own certs - https://www.bastillion.io/docs/installation/ssl/
