### ISSUE TITLE
Please add a comment how to install bastillion on FreeBSD (HOWTO included)

### ISSUE THREAD

**Issue by netchild** [bastillion-io/Bastillion#328]
Hi,

Bastillion has been committed (by me a while ago) to the FreeBSD ports collection.
It might be helpful to users if you could include a message like
the following on your website.

Thanks,
Alexander.

Proposal:

Bastillion can be installed on FreeBSD via the FreeBSD ports system.
To install via the binary package, simply run:
    `pkg install security/bastillion`
This will very quickly install a prebuilt binary using only highly-portable
optimizations, much like apt, yum, etc.
It can also be installed as a "FreeBSD port":
```
cd /usr/ports/security/bastillion
make install
```
To report issues with a FreeBSD port, please submit a PR at:
    https://www.freebsd.org/support/bugreports.html
For more information, visit https://www.freebsd.org/ports/index.html.

**Comment by skavanagh** [comment]
Thanks @netchild . Be sure and checkout the new release
