### ISSUE TITLE
Why not a medium license?

### ISSUE THREAD

**Issue by eprompc** [bastillion-io/Bastillion#330]
Hello.

Why not a license for small departments? My school has only 30 computers and I cannot buy a license because my institution prevents it.

Would there be any way to acquire a smaller license for nonprofit educational centers?

Thank you very much.

**Comment by skavanagh** [comment]
Email me at support@bastillion.io and I’ll hook you up with a key.  Thanks!

**Comment by skavanagh** [comment]
The latest version does not have a license key requirement
https://github.com/bastillion-io/Bastillion/releases/tag/v3.09.00

**Comment by eprompc** [comment]
Thanks you very much!!! I'll try it right now!!
Thanks!
