### ISSUE TITLE
XTerm scrollbar problem

### ISSUE THREAD

**Issue by ffabreti** [bastillion-io/Bastillion#335]
This is 3.09.00 release
Tested on  Linux Google Chrome 79.0.3945.130 64 bits

Scrollbar looks misplaced:

![Screenshot - 04_02_2020 , 14_48_42](https://user-images.githubusercontent.com/2559032/73773290-ab06bf00-4760-11ea-9e0c-c1b5d4e01742.png)

Result when resizing:

![Screenshot - 04_02_2020 , 14_50_36](https://user-images.githubusercontent.com/2559032/73773265-9cb8a300-4760-11ea-90dd-f465da1d6ed8.png)

**Comment by skavanagh** [comment]
I can’t seem to recreate this.  Can you try clearing your cache and try again
