### ISSUE TITLE
Database Password required upon first run ??

### ISSUE THREAD

**Issue by oywino** [bastillion-io/Bastillion#340]
I've installed **Bastillion 3.09** in  adocker container using j**dk-13.0.2_linux-x64_bin.deb**
Everytime I build a new container, during the very first run, Bastillion asks me

```
Please enter database password:
Please confirm database password:
```

Why is this, and what password am I supposed to give and for what purpose?

**Comment by skavanagh** [comment]
It's the password to the embedded database. You can do a 
```
export GEN_DB_PASS=true
```
as an environment var for docker and it will auto-generated the password

**Comment by oywino** [comment]
> It's the password to the embedded database.
Thank you! I never found this documented anywhere here, nor on the Bastillion web (?)
I'd like to know what Bastillion stores in this DB and where the DB is located. Also, I'd like to have all config/setting etc stored outside the container, but haven't found any documentation on the whereabouts of such data/files/DB. Is Bastillions folder structure documented somewhere?

**Comment by skavanagh** [comment]
the DB is located in the WEB-INF/classes/keydb folder as per

https://github.com/bastillion-io/Bastillion/blob/master/src/main/resources/BastillionConfig.properties#L58

everything you add to bastillion is stored in the DB.  Users, Profiles, Systems, etc..
