### ISSUE TITLE
H2 databases sometimes corrupted on service restart

### ISSUE THREAD

**Issue by heronimus** [bastillion-io/Bastillion#341]
It happen sometimes after Bastillion restart, the service won't up and says that db file corrupted.

Bastillion version : 3.09.00 (latest)
OS : Centos 7.7
Java version : jdk-11.0.4-11.0.4-ga.x86_64

Here the error log:

> 
> 2020-03-04 11:07:09.733:INFO:oejs.session:main: node0 Scavenging every 660000ms
> 2020-03-04 11:07:11,393 ERROR DBUtils - java.sql.SQLException: Cannot create PoolableConnectionFactory (Encryption error in file null [90049-199])
> java.sql.SQLException: Cannot create PoolableConnectionFactory (Encryption error in file null [90049-199])
> 	at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2385) ~[commons-dbcp2-2.5.0.jar:2.5.0]
> 	at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2110) ~[commons-dbcp2-2.5.0.jar:2.5.0]
> 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:1563) ~[commons-dbcp2-2.5.0.jar:2.5.0]
> 	at io.bastillion.manage.util.DBUtils.getConn(DBUtils.java:55) [classes/:?]
> 	at io.bastillion.common.db.DBInitServlet.init(DBInitServlet.java:111) [classes/:?]

> Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Encryption error in file null [90049-199]
> 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617) ~[h2-1.4.199.jar:1.4.199]
> 	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427) ~[h2-1.4.199.jar:1.4.199]
> 	at org.h2.message.DbException.get(DbException.java:194) ~[h2-1.4.199.jar:1.4.199]

> Caused by: java.lang.IllegalStateException: File corrupted in chunk 97978, expected check value 31893, got 31983 [1.4.199/6]
> 	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883) ~[h2-1.4.199.jar:1.4.199]
> 	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1071) ~[h2-1.4.199.jar:1.4.199]
> 	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186) ~[h2-1.4.199.jar:1.4.199]

Current workaround for this problem is frequently doing backup of the H2 DB.

**Comment by skavanagh** [comment]
so the stack trace reads to me that it's not able to connect to the database as in it's not there.  Is there anything that you are doing that could cause that?

You also might want to try setting auto_server to true in your BastillionConfig.properties

dbConnectionURL=jdbc:h2:keydb/bastillion;CIPHER=AES;AUTO_SERVER=TRUE

https://github.com/bastillion-io/Bastillion/blob/master/src/main/resources/BastillionConfig.properties#L58

That will allow more than one process to connect to the DB at one time (maybe you are running into that)

http://www.h2database.com/html/features.html?highlight=AUTO_SERVER&search=auto_server#auto_mixed_mode

**Comment by heronimus** [comment]
The database is still there, but yes you're correct, I've used some program to directly bulk insert to the H2 DB and sync the registered 'system' in Bastillion with centralized IP management periodically. It usually runs with no problem, but lately, it sometimes causes databases corrupt and makes Bastillion won't start like the error above.

And thanks, I think AUTO_SERVER=TRUE is something I looking for! 👍. Maybe we can mention this configuration too in the Bastillion documentation. I'm not too familiar with the H2 DB configuration, so to avoid multiple connections I shut down the Bastillion before starting my program to do the sync process. I also will look again at what makes the DB file corrupted when running my program.

I thinks this Issue is not coming from Bastillion, so I'll close this issue. Thanks @skavanagh ! 

Regards,
@heronimus
