### ISSUE TITLE
Retrieving Lost DB Pass

### ISSUE THREAD

**Issue by olvap377** [bastillion-io/Bastillion#342]
When Bastillion was setup initially using the "Bundled with Jetty" instructions, we don't know what the DB pass was setup as.

Contents of the config:
```
#Database user
dbUser=bastillion
#Database password
dbPassword=AES{DCrT4Kf4tsOFZpXwVsgHyQ==}
#Database JDBC driver
dbDriver=org.h2.Driver
#Connection URL to the DB
dbConnectionURL=jdbc:h2:keydb/bastillion;CIPHER=AES;AUTO_SERVER=TRUE
#Max connections in the connection pool
maxActive=25
#When true, objects will be validated before being returned by the connection pool
testOnBorrow=true
#The minimum number of objects allowed in the connection pool before spawning new ones
minIdle=2
#The maximum amount of time (in milliseconds) to block before throwing an exception when the connection pool is exha$
maxWait=15000
```

I have tried connecting with `org.h2.tools.Shell` with no luck. 

How would I go about "decrypting" the dbPassword? I can login to the webUI with a Full Access admin account, would I use the admin credentials in the -user and -password flags?

I know the format is "dbpass userpass" but does that dbpass need to be in plain text? 

Tried the below with no result:
```
org.h2.tools.ChangeFileEncryption -dir /opt/Bastillion-jetty/jetty/bastillion/WEB-INF/classes/keydb/ -db bastillion -cipher=AES -decrypt AES{DCrT4Kf4tsOFZpXwVsgHyQ==}
```

**Comment by olvap377** [comment]
@skavanagh Would you have any insight as to how to proceed?

**Comment by skavanagh** [comment]
It's very difficult to get that password (even for me).  I'll have to write
something to get that out. Email me at support@bastillion.io and I'll see
what I can do.

**Comment by olvap377** [comment]
Thanks again for the help.
