### ISSUE TITLE
Terminal is empty (black screen)

### ISSUE THREAD

**Issue by maciekberry** [bastillion-io/Bastillion#347]
Hello,

I am sure I am missing something obvious, and I am sorry for this.

I am trying to evaluate Bastillion, but I am unable to make the web terminal work. Every time I open it, the screen is black (even after I select "Reset Size"). I cannot type, I do not see any output.
However, in the logs of the server, the ssh session is correctly established - it's just the terminal itself does not work.

Is it a bug? Or just that I messed something up?

PS. Tried in Chrome and Firefox on Mac.

**Comment by skavanagh** [comment]
Hi Maciek -

Sounds like web sockets is being blocked. Do you have a firewall or
load-balancer in the mix?

**Comment by maciekberry** [comment]
Indeed, the problem was websockets. Not the firewall, but the reverse proxy was not proxying the wss (and returning 404). I missed it somehow in the logs, sorry.

However, configuring apache for proxying websockets via ssl is a bit tricky, please find below my configuration (you can add it to the official documentation of course):

        <VirtualHost _default_:443>

                ServerName <your server name>

                SSLEngine on
                SSLCertificateFile      /etc/<certif file path>
                SSLCertificateKeyFile /etc/<private key path>

                RewriteEngine On
                RewriteCond %{HTTP:Upgrade} =websocket [NC]
                RewriteRule /(.*)           wss://localhost:8443/$1 [P,L]

                SSLProxyEngine on
                SSLProxyVerify none
                SSLProxyCheckPeerCN off
                SSLProxyCheckPeerName off
                SSLProxyCheckPeerExpire off

                <Proxy *>
                Require all granted
                </Proxy>

                ProxyPass / https://127.0.0.1:8443/
                ProxyPassReverse / https://127.0.0.1:8443/

        </VirtualHost>
