### ISSUE TITLE
default admin password not working anymore

### ISSUE THREAD

**Issue by CargaisonTuba** [bastillion-io/Bastillion#351]
Hi, I don't know why, I always logged using admin and default "changeme" password. Always clicked on "See later" button when the 2FA window appeared. But this time I clicked "OK" by mistake and since then the password doesn't work anymore.
Tried to restart Bastillion, didn't work

**Comment by skavanagh** [comment]
all you should have to do is set this property to disabled and restart
https://github.com/bastillion-io/Bastillion/blob/master/src/main/resources/BastillionConfig.properties#L28
