### ISSUE TITLE
Bastillion uses vulnerable log4j

### ISSUE THREAD

**Issue by netchild** [bastillion-io/Bastillion#404]
Hi,

log4j in bastillion is vulnerable.
Recommended action: update log4j.
Workaround: use "-Dlog4j2.formatMsgNoLookups=True" in java arguments on startup, or set env variable "LOG4J_FORMAT_MSG_NO_LOOKUPS=true" before starting it.

Bye,
Alexander.

**Comment by skavanagh** [comment]
https://github.com/bastillion-io/Bastillion/commit/b4b5b01fe684413790318485027605d6487de2d0
