### ISSUE TITLE
How to upgrade properly ? 

### ISSUE THREAD

**Issue by vsilent** [bastillion-io/Bastillion#405]
How can I upgrade bastilion without losing any data ?

**Comment by Danno040** [comment]
I'm getting errors like this when running `v3.12` but it works fine in `v3.11`:

> Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "The write format 1 is smaller than the supported format 2 [2.0.202/5]" [50000-202]

Seems related to to the upgrade of H2.

**Comment by vsilent** [comment]
Are there any instructions on how to upgrade or I have just to unpack the source code and replace the files?

**Comment by Danno040** [comment]
There are instructions on the [release page](https://github.com/bastillion-io/Bastillion/releases/tag/v3.12.00):

To migrate from 3.10.00

- Backup previous bastillion.h2.db data store (possibly named keybox.h2.db)
- Copy old jetty/bastillion/WEB-INF/classes/keydb folder (and it's contents) to the jetty/bastillion/WEB-INF/classes directory of the new installation.
- Copy old jetty/bastillion/WEB-INF/classes/bastillion.jceks to the /jetty/bastillion/WEB-INF/classes directory of the new installation.
- Copy old jetty/bastillion/WEB-INF/classes/BastillionConfig.properties to the /jetty/bastillion/WEB-INF/classes directory of the new installation.
- Adjust settings or copy as needed for the jaas.conf, log4j2.xml, keystore, jetty-ssl.xml and jetty-http.xml

However, when I follow them, I get errors connecting to the DB.

**Comment by netchild** [comment]
I can confirm the message "The write format 1 is smaller than the supported format 2 [2.0.202/5]".

**Comment by vsilent** [comment]
"However, when I follow them, I get errors connecting to the DB."  - same here

**Comment by tswestendorp** [comment]
My upgraded instance is able to start but I'm not able to authenticate using previous credentials, when switching back to 3.11.01 they work fine

**Comment by skavanagh** [comment]
@netchild  - yes it looks like it's a compatibility thing - this should help https://github.com/h2database/h2database/issues/3214#issuecomment-982643991

You can export it with 1.4.2 and import it with 2.0.202

And there is this `org.h2.tools.Upgrade.upgrade()` thing that looks easier, but I haven't tired it.

**Comment by netchild** [comment]
> @netchild - yes it looks like it's a compatibility thing - this should help [h2database/h2database#3214 (comment)](https://github.com/h2database/h2database/issues/3214#issuecomment-982643991)
> 
> You can export it with 1.4.2 and import it with 2.0.202

First I validated with bastillion 3.11_01 that it can read the users and hosts. Then I stopped 3.11_01 and did this:

# java -cp /usr/local/jetty_bastillion/bastillion/WEB-INF/lib/h2-1.4.200.jar org.h2.tools.Script -url jdbc:h2:/usr/local/jetty_bastillion/bastillion/WEB-INF/classes/keydb/bastillion -user bastillion -script backup.zip -password '<base64 decode of password string in properties file>' -options compression zip
File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at org.h2.tools.Script.process(Script.java:118)
        at org.h2.tools.Script.runTool(Script.java:100)
        at org.h2.tools.Script.main(Script.java:45)
Caused by: java.lang.IllegalStateException: Store header is corrupt: nio:/usr/local/jetty_bastillion/bastillion/WEB-INF/classes/keydb/bastillion.mv.db [1.4.200/6]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:728)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:396)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 19 more

I did not try the recover. Bastillion can open it and list hosts and users, so I assume it is not really corrupt.

The DB-PW in the properties file is there as "AES{<base64 encoded string>}". The base64-decode of this string inside {} looks like a valid PW to me (can't find the ASCII of the PW where I expect it to be stored in the PW-safe). At least it is a string, and not binary data.

Any idea what is wrong here?

> And there is this `org.h2.tools.Upgrade.upgrade()` thing that looks easier, but I haven't tired it.

The URL you quoted tells it will not work.

**Comment by Danno040** [comment]
@skavanagh : Could you describe how we can do the export/import?

My experience is in line with @netchild 's. I'm not sure how to tell the h2 tools how to unencrypt the DB in the way Bastillion does.

**Comment by netchild** [comment]
Ok... writing the base64 decode into a file reveals binary data... how is the pw encoded in the BastillionConfig.properties?

**Comment by skavanagh** [comment]
﻿It’s AES encrypted with the key that’s generated on startup. I take it you auto generated the password?

**Comment by Danno040** [comment]
Here are the steps that worked for me:

```bash
export OLD_B_PATH=/path/to/bastillion/v3.11/jetty/bastillion/WEB-INF
export NEW_B_PATH=/path/to/bastillion/v3.12/jetty/bastillion/WEB-INF
export DB_PW="YourDbsPasswordInPlainText"
# Stop v3.11 first
java -cp $OLD_B_PATH/lib/h2-1.4.200.jar org.h2.tools.Script -url "jdbc:h2:$OLD_B_PATH/classes/keydb/bastillion;CIPHER=AES;" -password "filepwd $DB_PW" -user bastillion -script backup.zip -options compression zip
java -cp $NEW_B_PATH/lib/h2-2.0.202.jar org.h2.tools.Script -url "jdbc:h2:$NEW_B_PATH/classes/keydb/bastillion;CIPHER=AES;" -password "filepwd $DB_PW" -user bastillion -script backup.zip -options compression zip
```

If you don't know (or forgot your DBs password), I created a "Dump" utility in `io.bastillion.manage.util` which looked like this:

```java
package io.bastillion.manage.util;

import io.bastillion.common.util.AppConfig;

public class Dump {
  public static void main (String[] arg) {
          System.out.println(AppConfig.decryptProperty("dbPassword"));
  }
}
```

when run with real configuration, will print your db password.

**Comment by netchild** [comment]
@Danno040 How do you run the dump? I've used "javac -cp /path/to/bastillion/WEB-INF/classes Dump.java" and have it in the util folder. But then it complains about a missiong org/slf4j/LoggerFactory (command line used: "java -cp /usr/local/jetty_bastillion/bastillion/WEB-INF/classes:/usr/local/jetty_bastillion/bastillion/WEB-INF/lib/ io.bastillion.manage.util.Dump").

**Comment by netchild** [comment]
And your second java-line has a copy&paste issue (RunScript instead of Script is supposed to be there.

**Comment by Danno040** [comment]
> How do you run the dump?

@netchild : You just need to include the jars with `*` in your classpath:

```
java -cp /usr/local/jetty_bastillion/bastillion/WEB-INF/classes:/usr/local/jetty_bastillion/bastillion/WEB-INF/lib/* io.bastillion.manage.util.Dump
```

**Comment by netchild** [comment]
Works (I was quoting the * so that the shell doesn't expand). Thanks!

**Comment by skavanagh** [comment]
`org.h2.tools.Upgrade.upgrade()` works great! I was able to use it to create an executable jar to upgrade H2 1.x -> 2.x and added it to the release instructions

https://github.com/bastillion-io/Bastillion/releases/tag/v3.12.01
