### ISSUE TITLE
Bastillion can't connect to hardened ssh servers (missing encryption algorithms in bastillion)

### ISSUE THREAD

**Issue by netchild** [bastillion-io/Bastillion#409]
Hi,

https://www.sshaudit.com/hardening_guides.html contains guides for a hardened ssh setup. Bastillion can't connect to servers hardened this way (seems only unsupported encryption algorithms are allowed by the hardened config).

Bye,
Alexander.

**Comment by skavanagh** [comment]
You can use a ecdsa key per https://github.com/bastillion-io/Bastillion/blob/master/src/main/resources/BastillionConfig.properties#L8

Also I did switch to use this library - https://github.com/mwiede/jsch
which is more actively maintained.

**Comment by skavanagh** [comment]
https://github.com/bastillion-io/Bastillion/commit/582d400eff84747606405ecf7de5cde504e268cf
