### ISSUE TITLE
Problem add new system in last updates

### ISSUE THREAD

**Issue by IvanShilov** [bastillion-io/Bastillion#418]
Hi

in v3.12.02
After the update, it is impossible to add new systems 

in v3.13.00
After the update, it cleared all previously introduced systems and it is impossible to add new systems

stay v3.12.02 :)

**Comment by skavanagh** [comment]
For 3.13 - try running the upgrade with th bastillion-upgrade-4.00.01.jar
<https://github.com/bastillion-io/Bastillion/releases/download/v3.13.00/bastillion-upgrade-4.00.01.jar>
(don't
use the 4.00.00.jar)

**Comment by IvanShilov** [comment]
Yes fine. There may have been some errors when updating the previous time.
Thank you

It will be cool if you add a filter to the system menu / users, something like in the profile menu. When many items are added, it can be difficult to find the right one at times ;)
