### ISSUE TITLE
automatically deletes exisiting authorized_keys

### ISSUE THREAD

**Issue by c2h2** [bastillion-io/Bastillion#448]
After trying for some minutes, it deletes all the entries of my existing authorized_keys of my exisiting host.   🙈 and replaces with own Bastillion globalkey keys. is this expected?

**Comment by skavanagh** [comment]
Yes - https://github.com/bastillion-io/Bastillion#managing-ssh-keys

**Comment by c2h2** [comment]
very secure design indeed!
