### ISSUE TITLE
Stuck during installation.

### ISSUE THREAD

**Issue by jonathansaha** [bastillion-io/Bastillion#521]
Hello,

I have this weird problem, during installing the software it gets stuck at one point and does not go any further. I am putting the steps I followed below,

1. apt update -y && apt upgrade -y
2. apt install default-jdk
3. java --version
    openjdk 17.0.8 2023-07-18
    OpenJDK Runtime Environment (build 17.0.8+7-Debian-1deb12u1)
    OpenJDK 64-Bit Server VM (build 17.0.8+7-Debian-1deb12u1, mixed mode, sharing)
4. Then added these two line in /etc/profile at the end.
    export JAVA_HOME=/usr/lib/jvm/default-java
    export PATH=$JAVA_HOME/bin:$PATH
5. cd /opt
6. Downloaded the software.
   wget https://github.com/bastillion-io/Bastillion/releases/download/v3.15.00/bastillion-jetty-v3.15_00.tar.gz
7. Unziped the software.
   tar xfz bastillion-jetty-v3.15_00.tar.gz -C /opt
8. Went into the unzipped directory.
   cd Bastillion-jetty/
9. Started the installation script.
  ./startBastillion.sh 

After that the prompt asks for database password. After giving the password it just gets stuck.
![image](https://github.com/bastillion-io/Bastillion/assets/14842609/ec640cac-1531-4ad1-ab91-49dd873b4cd7)

Pressing enter just adds blank line in terminal. The process can be stopped with Crtl+Z.

This system is a VM, 8 core, 4GB ram, 50GB storage, Debian 12.
I have also tried with same spec in Ubuntu 22.
I am using Proxmox VE for hypervisor. And also have tried on proxmox's ubuntu container.
I have a feeling I am making a very silly mistake somewhere.

I have tried the same steps on huawei cloud instance, on Ubuntu 22(similar thing to a aws or azure), the software ran on first try without any issue. But I need to run it on premise, which runs proxmox. Has anyone faced this kind of issue?

Thanks for taking your time to read through the post.

**Comment by IvanShilov** [comment]
What are in your logs?

**Comment by jonathansaha** [comment]
![image](https://github.com/bastillion-io/Bastillion/assets/14842609/3e4d8834-733d-4330-9d88-03c1f6682f10)

**Comment by i-fix-retarded-bugs** [comment]
Amazing

**Comment by i-fix-retarded-bugs** [comment]
@jonathansaha Have you managed to fix this issue?

**Comment by jonathansaha** [comment]
It works on proxmox 8.2 at ubuntu VMs fine.
I still could not make it work on proxmox 7.1 at ubuntu VMs, which was my environment at the time of opening the issue.
I dont know why it acted this way, hypervisor type or version number should not be any issue inside a VM, right?
I am closing this issue.
