### ISSUE TITLE
Add option to disable or limit the number of times the "Skip for Now" button appears for MFA

### ISSUE THREAD

**Issue by WRJFontenot** [bastillion-io/Bastillion#83]
Currently the "Skip for Now" button can't be disabled or limited in order to force users to configure MFA.  Please add an option to disable and/or limit the number of times this button appears before a user is forced to configure MFA in order to login.
# enable two-factor authentication

enableOTP=true
# force two-factor authentication after this number of logins.  0 disables "Skip for Now" button.

enforceOTP=3

**Comment by skavanagh** [comment]
Added option to make OTP mandatory. See https://github.com/skavanagh/KeyBox/issues/102

Still not a way to set a number of "Skips"
